<?php
if($this->status == 0) {
    echo' Kullanıcı Girişi
<form action="/user/index/login" method="post">
    <input type="text" placeholder="email" name="email_form"><br>
    <input type="text" placeholder="şifre" name="password_form"><br>
    <input type="submit" name="login"  value="Giriş Yap">
</form>';
}
elseif($this->status == 1){

   header("Location: http://rdcproject/hangman/index");

}

