<form role="form" style="width:30%;">

    <div class="form-group">
        <label for="exampleInputEmail1">School:</label>
        <input type="text" class="form-control" id="exampleInputEmail1" name="school" value="<?php echo $this->user['school']; ?>">
    </div>

    <div class="form-group">
        <label for="exampleInputPassword1">Birthday:</label>
        <input type="date" class="form-control" id="exampleInputPassword1" name="birthday" value="<?php echo $this->user['birthday']; ?>">
    </div>

</form>

